DROP TABLE IF EXISTS hits;


CREATE TABLE IF NOT EXISTS hits (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  app VARCHAR(255) NOT NULL,
  uri VARCHAR(512),
  ip VARCHAR(255) NOT NULL,
  created timestamp
);